# Generated by Django 4.0.6 on 2022-07-29 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("searches", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="search",
            options={"verbose_name_plural": "searches"},
        ),
        migrations.AlterField(
            model_name="traveltimerequirement",
            name="place_kind",
            field=models.CharField(
                blank=True,
                choices=[
                    ("bus_station", "Bus station"),
                    ("establishment", "Establishment"),
                    ("gym", "Gym"),
                    ("light_rail_station", "Light rail station"),
                    ("park", "Park"),
                    ("premise", "Premise"),
                    ("restaurant", "Restaurant"),
                    ("school", "School"),
                    ("subway_station", "Subway station"),
                    ("train_station", "Train station"),
                ],
                max_length=32,
            ),
        ),
    ]
