# Generated by Django 4.0.6 on 2022-07-29 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("searches", "0002_alter_search_options_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="traveltimerequirement",
            name="valid_place_or_place_kind",
        ),
        migrations.AddConstraint(
            model_name="traveltimerequirement",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("place__isnull", False), ("place_kind", "")),
                    models.Q(
                        ("place__isnull", True),
                        models.Q(("place_kind", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="valid_place_or_place_kind",
            ),
        ),
    ]
