# Generated by Django 4.0.6 on 2022-07-29 09:49

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Amenity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("google_id", models.CharField(max_length=128)),
                ("name", models.TextField()),
                ("location", django.contrib.gis.db.models.fields.PointField(srid=4326)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("bus_station", "Bus station"),
                            ("gym", "Gym"),
                            ("light_rail_station", "Light rail station"),
                            ("park", "Park"),
                            ("restaurant", "Restaurant"),
                            ("subway_station", "Subway station"),
                            ("train_station", "Train station"),
                        ],
                        max_length=32,
                    ),
                ),
            ],
        ),
    ]
