# Generated by Django 4.0.6 on 2022-07-29 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0002_amenity"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="amenity",
            options={"verbose_name_plural": "amenities"},
        ),
        migrations.AlterModelOptions(
            name="property",
            options={"verbose_name_plural": "properties"},
        ),
        migrations.AddField(
            model_name="property",
            name="imported_amenities_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
