# Generated by Django 4.0.6 on 2022-07-29 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0005_propertyplace"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="propertyplace",
            constraint=models.UniqueConstraint(
                fields=("property", "place"), name="property_place_unique"
            ),
        ),
    ]
