# Generated by Django 4.0.6 on 2022-07-29 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0006_propertyplace_property_place_unique"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="propertyplace",
            options={},
        ),
        migrations.AlterField(
            model_name="propertyplace",
            name="place",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="property_places",
                to="properties.place",
            ),
        ),
        migrations.AlterField(
            model_name="propertyplace",
            name="property",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="property_places",
                to="properties.property",
            ),
        ),
    ]
